---
# Ansible Galaxy requirements
# Install: ansible-galaxy install -r requirements.yml

collections:
  - name: community.docker
    version: ">=3.4.0"
  - name: community.general
    version: ">=8.0.0"

